spring:
  application:
    name: client
    
server:
  port: 8890

eureka:
  instance:
    nonSecurePort: 8890
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    
ribbon:
  eureka:
    enabled: true
    
logging:
  level:
    com.netflix.discovery: 'WARN'